### ISSUE TITLE
accented lower case characters are jarring

### ISSUE THREAD

**Issue by neilb** [eigilnikolajsen/commit-mono#40]
For example, in "café", the "e" looks like it's been rendered in a different font / size:

![Screenshot 2023-09-07 at 12 44 17](https://github.com/eigilnikolajsen/commit-mono/assets/478461/4b455128-96a9-4b69-b974-11cd86630803)

I realise there may not be much you can do about this, and I may get used to it, but right now it's jarring.

**Comment by eigilnikolajsen** [comment]
That's because it is rendered in a different font. Commit Mono does support the character `é`, so I think the problem is on your side. I have seen the option of displaying non-ascii characters using a fallback font in some editors/terminals. Turning that off should render `é` in Commit Mono correctly. I think that's where your issue lies.

**Comment by neilb** [comment]
Bingo! Thank you, that was exactly the problem. I changed the config for iTerm, and now all is hunky-dory.
