### ISSUE TITLE
Add ℕ ℤ ⊢ λ

### ISSUE THREAD

**Issue by eigilnikolajsen** [eigilnikolajsen/commit-mono#9]
Add these characters in the next release

**Comment by ashton314** [comment]
I'd love the following sets of characters:

 - All Greek letters
 - All math blackboard-bold characters (not just ℕ ℤ, but also for all the other sets)
 - Common set operators (∈∅∪∩⊂ etc.)

**Comment by eigilnikolajsen** [comment]
I will add when I have time. I also got a request to add [U+2714 HEAVY CHECK MARK], so just putting it here.

**Comment by LudvikGalois** [comment]
Can I also request `⇒` [U+212D RIGHTWARDS DOUBLE ARROW]? It's a blocker on me using this font, because it turns up in Haskell from time to time - some (albeit not many) Haskell projects use formatters which enforce UnicodeSyntax.

The full list of characters that need to be supported for Haskell's unicode syntax can be found here https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/unicode_syntax.html but, whilst `⇒` is a character that turns up very frequently, the rest of the unsupported characters are rarities (the arrow-tailed characters being rare to the point that I've never seem them in the wild).

**Comment by eigilnikolajsen** [comment]
@LudvikGalois nice, I will add those when I have time. I suppose they are all monospaced and not like the ligature => that takes up 2 characters

**Comment by LudvikGalois** [comment]
> I suppose they are all monospaced and not like the ligature => that takes up 2 characters

Correct.

**Comment by eigilnikolajsen** [comment]
Hello, I have added most of the issue in [version 1.135](https://github.com/eigilnikolajsen/commit-mono/releases/tag/1.135). Greek and Haskell's unicode syntax is now supported.

@ashton314 I have filed a new issue for the addition of double stroke letters. It is quite time consuming, so I will see when I get around to do it.
